name: Publish new versions of the RuOtvet to PyPI.
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependences
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
        run: |
          pip3 install setuptools wheel twine
          python setup.py sdist bdist_wheel
      - name: Uploading to PyPI
      - uses: pypa/gh-action-pypi-publish@v1.4.1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
